import liquid from '@/lib/liquid';

const TEMPLATE_MESSAGE = (
  `${liquid.comment('\tThis file is generated by webpack.\n\tDo not edit it directly.', '\n')}\n`
);

/** Generate a text block to assign a liquid asset variable */
const assetVarBlock = ({ name, file, variable }) => {
  let block = '';

  block += liquid.comment(name);
  block += liquid.variable('assetPath', `'${file}' | asset_url | split: '?'`);
  block += `{% assign ${liquid.variableName(variable)} = assetPath[0] %}\n`;

  return block;
};

const liquidTemplate = (assets) => TEMPLATE_MESSAGE + assets
  .reduce((str, asset) => str + assetVarBlock(asset), '');

export default liquidTemplate;
