import comment from '@/lib/liquid/comment';

const message = [
  'This file is generated by webpack.',
  'Do not edit it directly.',
].map((l) => `\t${l}`).join('\n');

const TEMPLATE_MESSAGE = (
  `${comment(message, true)}\n`
);

export default TEMPLATE_MESSAGE;
