import comment from '@/lib/liquid/comment';

const TEMPLATE_MESSAGE = (
  `${comment('\tThis file is generated by webpack.\n\tDo not edit it directly.', '\n')}\n`
);

export default TEMPLATE_MESSAGE;
